modLoader="javafml"
loaderVersion="[40,)"
license="Public Domain"

itemIcon="dummmmmmy:target_dummy_placer" #catalogue icon

configuredBackground= "minecraft:textures/blocks/oak_planks.png"
logoFile="logo.png"

[[mods]]
    modId="dummmmmmy"
    version="${file.jarVersion}" #mandatory
    displayName="MmmMmmMmmMmm"
    credits="bonusboni, Gooigipunch, Plantkillable"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm"
    authors="MehVahdJukaar, bonusboni"
    description='''don't hurt me pls :S'''

[[dependencies.dummmmmmy]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dummmmmmy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20]"
    ordering="NONE"
    side="BOTH"




