modLoader="javafml"
loaderVersion="[31,)"
license="don't know what to put here :/"

itemIcon="dummmmmmy:target_dummy_placer" #catalogue icon

configuredBackground= "minecraft:textures/blocks/oak_planks.png"
logoFile="logo.png"

[[mods]]
    modId="dummmmmmy"
    version="1.18-1.5.0" #mandatory
    displayName="MmmMmmMmmMmm"
    credits="bonusboni, Gooigipunch"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm"
    authors="MehVahdJukaar, bonusboni"
    description='''don't hurt me pls :S'''

[[dependencies.dummmmmmy]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dummmmmmy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19]"
    ordering="NONE"
    side="BOTH"




